import { ShieldAlert, GitBranch, Navigation, TrendingUp, DollarSign, Megaphone, Crown } from "lucide-react"

export const AGENTS_CONFIG = [
  {
    id: "risk_sentinel",
    name: "Risk Sentinel",
    tagline: "I find threats before they find you",
    icon: ShieldAlert,
    emoji: "🛡️",
    role: "Proactive Risk Detection & Scoring",
    model: "Llama-3.3-70B",
    modelProvider: "Groq",
    modelColor: "#f97316",
    modelIcon: "⚡",
    color: "from-red-500/20 to-orange-500/20",
    borderColor: "border-red-500/30",
    accentColor: "#ef4444"
  },
  {
    id: "supply_optimizer",
    name: "Supply Optimizer",
    tagline: "I find you the best supplier, always",
    icon: GitBranch,
    emoji: "🔗",
    role: "Demand-Supply Matching + Alternate Sourcing",
    model: "Claude 3.5 Sonnet",
    modelProvider: "AWS Bedrock",
    modelColor: "#a78bfa",
    modelIcon: "🧠",
    color: "from-violet-500/20 to-purple-500/20",
    borderColor: "border-violet-500/30",
    accentColor: "#7c3aed"
  },
  {
    id: "logistics_navigator",
    name: "Logistics Navigator",
    tagline: "I find the fastest, cheapest route — always",
    icon: Navigation,
    emoji: "🧭",
    role: "Route Optimization + Carrier Selection",
    model: "Gemini 1.5 Pro",
    modelProvider: "Google",
    modelColor: "#22d3ee",
    modelIcon: "💡",
    color: "from-cyan-500/20 to-blue-500/20",
    borderColor: "border-cyan-500/30",
    accentColor: "#0891b2"
  },
  {
    id: "market_intelligence",
    name: "Market Intelligence",
    tagline: "I know what's coming before the market does",
    icon: TrendingUp,
    emoji: "📈",
    role: "Trend Analysis + Competitive Intelligence",
    model: "Llama-3.3-70B",
    modelProvider: "Groq",
    modelColor: "#f97316",
    modelIcon: "⚡",
    color: "from-amber-500/20 to-yellow-500/20",
    borderColor: "border-amber-500/30",
    accentColor: "#d97706"
  },
  {
    id: "finance_guardian",
    name: "Finance Guardian",
    tagline: "I protect every dollar and maximize every investment",
    icon: DollarSign,
    emoji: "💰",
    role: "Financial Impact Analysis + ROI Optimization",
    model: "Claude 3.5 Sonnet",
    modelProvider: "AWS Bedrock",
    modelColor: "#a78bfa",
    modelIcon: "🧠",
    color: "from-emerald-500/20 to-green-500/20",
    borderColor: "border-emerald-500/30",
    accentColor: "#059669"
  },
  {
    id: "brand_protector",
    name: "Brand Protector",
    tagline: "I protect the brand when supply chains break",
    icon: Megaphone,
    emoji: "📣",
    role: "Brand Sentiment + Crisis Communication",
    model: "GPT-4o",
    modelProvider: "OpenAI",
    modelColor: "#34d399",
    modelIcon: "🤖",
    color: "from-pink-500/20 to-rose-500/20",
    borderColor: "border-pink-500/30",
    accentColor: "#e11d48"
  },
  {
    id: "moderator",
    name: "Moderator Agent",
    tagline: "I run the debate and deliver the final verdict",
    icon: Crown,
    emoji: "👑",
    role: "Route → Debate → Synthesize → Decide",
    model: "Llama-3.3-70B",
    modelProvider: "Groq",
    modelColor: "#f97316",
    modelIcon: "⚡",
    color: "from-indigo-500/20 to-purple-500/20",
    borderColor: "border-indigo-500/30",
    accentColor: "#6366f1"
  }
]
